### ISSUE TITLE
CUDA out of memory. 

### ISSUE THREAD

**Issue by jeromedejaegher** [Elvinky/IEGAN#1]
Hi, thank you for this sharing. I tried to run your code on GTX1650Ti (4Go), but ran out of memory.
Is there any custom settings to try your code with limited memory ? I tried --light=True, but without success. Regards,

**Comment by Elvinky** [comment]
Glad to answer your question. GTX 1650Ti only has 4GB of GPU memory, while IEGAN must have at least 10GB of GPU memory. Now we don't have a better way to reduce GPU memory and we have updated the memory usage in the README. Regarding light, IEGAN doesn't have an option about light, but our negligence caused it, and it has been fixed now. Please feel free to contact me if you have any questions.

**Comment by jeromedejaegher** [comment]
Thanks for this clear answer. Regards,
